version: '2.3'

services:
  example.com:
    depends_on:
      - admin.example.com
    container_name: example.com
    image: example.com
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: example.com
    ports:
      - 80
    networks:
      - proxy
      - internal

  admin.example.com:
    depends_on:
      - db.example.com
    container_name: admin.example.com
    image: admin.example.com
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/wp-content
    environment:
      VIRTUAL_HOST: admin.example.com
      FS_METHOD: direct
      DB_HOST: db.example.com
    ports:
      - 80
    networks:
      - proxy
      - internal

  db.example.com:
    container_name: db.example.com
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

volumes:
  wp_data:
  db_data:

networks:
  proxy:
    external: true
  internal:
    external: true
