version: '2.3'

services:
  example.local:
    depends_on:
      - admin.example.local 
    container_name: example.local
    image: example.local:0.1.0
    ports:
      - 80
    networks:
      - backend
    environment:
      VIRTUAL_HOST: example.local,www.example.local
      # LETSENCRYPT_HOST: example.local,www.example.local
      # LETSENCRYPT_EMAIL: user@example.local
  admin.example.local:
    depends_on:
      - db.example.local
    container_name: admin.example.local
    image: willopez/wordpress:0.2.0
    ports:
      - 80
    networks:
      - backend
    environment:
      VIRTUAL_HOST: admin.example.local,www.admin.example.local
      DB_NAME: wp
      DB_USER: wp
      DB_PASSWORD: wp
      DB_HOST: db.example.local
      WP_DEBUG: "true"
      FS_METHOD: direct
      # LETSENCRYPT_HOST: example.admin.local,www.example.admin.local
      # LETSENCRYPT_EMAIL: user@example.admin.local
    volumes:
      - ./wordpress/wp-content:/var/www/wp-content

  db.example.local:
    container_name: db.example.local
    image: mariadb:10.3
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

networks:
  backend:
    external:
      name: backend
